image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd back-end && npm install
    command: cd back-end; PORT=3001 npm start
    name: Back-end
  - init: cd front-end && npm install
    name: Front-end
    command: cd front-end; PORT=8080 REACT_APP_SUBMIT_URL=https://3001-${GITPOD_WORKSPACE_URL#https://}/submit npm start
    openMode: split-right    

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3001
    onOpen: notify
