image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd front-end && npm install && cd ../back-end && npm install
    command: cd front-end; npm start
    command: cd back-end; npm start

ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: notify
