image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd back-end && npm install
    name: Init back-end
  - init: cd front-end && npm install
    name: Init front-end
  - command: cd front-end; npm start
    name: Start front end
  - command: cd back-end; npm start
    name: Start back end
    openMode: split-right

ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: notify
